### ISSUE TITLE
Out of CUDA Memory

### ISSUE THREAD

**Issue by davidsonic** [rxtan2/Learning-Similarity-Conditions#3]
Although the batch size is reduced to 16 and during training it takes only 2000mb, the program crashes at the end of the first epoch with the following error: 
Loading Train Dataset
Loading Test Dataset
Loading Val Dataset
  + Number of params: 2805796
/media/sdb/jiali/env/lib/python3.6/site-packages/torch/nn/modules/container.py:92: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)
Train Epoch: 1 [0/10000]        Loss: 0.1986 (0.1986)   Acc: 0.00% (0.00%)      Emb_Norm: 0.75 (0.75)
Train Epoch: 1 [1600/10000]     Loss: 0.1626 (0.1632)   Acc: 0.00% (0.00%)      Emb_Norm: 0.67 (0.70)
Train Epoch: 1 [3200/10000]     Loss: 0.1936 (0.1545)   Acc: 0.00% (0.00%)      Emb_Norm: 0.60 (0.67)
Train Epoch: 1 [4800/10000]     Loss: 0.1883 (0.1471)   Acc: 0.00% (0.00%)      Emb_Norm: 0.58 (0.64)
Train Epoch: 1 [6400/10000]     Loss: 0.0961 (0.1420)   Acc: 0.00% (0.00%)      Emb_Norm: 0.57 (0.63)
Train Epoch: 1 [8000/10000]     Loss: 0.1021 (0.1390)   Acc: 0.00% (0.00%)      Emb_Norm: 0.55 (0.62)
Train Epoch: 1 [9600/10000]     Loss: 0.0972 (0.1369)   Acc: 0.00% (0.00%)      Emb_Norm: 0.57 (0.61)
Traceback (most recent call last):
  File "main.py", line 361, in <module>
    main()
  File "main.py", line 168, in main
    acc = test(val_loader, tnet, criterion, epoch)
  File "main.py", line 258, in test
    dista, distb, _, _, _ = tnet(data1, data2, data3, c)
  File "/media/sdb/jiali/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/jiali/amazon/Learning-Similarity-Conditions/tripletnet.py", line 62, in forward
    tmp_embedded_y, masknorm_norm_y, embed_norm_y, tot_embed_norm_y = self.embeddingnet(y, concept_idx)
  File "/media/sdb/jiali/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/jiali/amazon/Learning-Similarity-Conditions/csn.py", line 48, in forward
    embedded_x = self.embeddingnet(x)
  File "/media/sdb/jiali/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/jiali/amazon/Learning-Similarity-Conditions/Resnet_18.py", line 98, in forward
    x = self.layer1(x)
  File "/media/sdb/jiali/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/sdb/jiali/env/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/media/sdb/jiali/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/jiali/amazon/Learning-Similarity-Conditions/Resnet_18.py", line 36, in forward
    out = self.conv1(x)
  File "/media/sdb/jiali/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/sdb/jiali/env/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 343, in forward
    return self.conv2d_forward(input, self.weight)
  File "/media/sdb/jiali/env/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 340, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 14.00 MiB (GPU 0; 7.76 GiB total capacity; 6.13 GiB already allocated; 16.75 MiB free; 326.85 MiB cached)

Any suggestions?

**Comment by davidsonic** [comment]
Just realized that val_loader has a fixed batch size.
